### ISSUE TITLE
doesn't work on Elixir 1.3.3 with Phoenix 1.2.1

### ISSUE THREAD

**Issue by ynjiun** [oarrabi/elixir-echo-bot#1]

**Comment by ynjiun** [comment]
when I run mix phoenix.server under elixir 1.3.3 and phoenix 1.2.1, I got this error:

```
paul@learning:~/elixir/phoenix_facebook_echo_bot$ mix phoenix.server
==> httpotion
Compiling 1 file (.ex)

== Compilation error on file lib/httpotion.ex ==
** (ArgumentError) Access is not a protocol
    (elixir) lib/protocol.ex:76: Protocol.assert_protocol!/2
    lib/httpotion.ex:292: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

could not compile dependency :httpotion, "mix compile" failed. You can recompile this dependency with "mix deps.compile httpotion", update it with "mix deps.update httpotion" or clean it with "mix deps.clean httpotion"
```

I tried to follow the advice from: https://github.com/myfreeweb/httpotion/issues/87

Then when I do mix  deps.update --all, then I got the following errors:

```
paul@learning:~/elixir/phoenix_facebook_echo_bot$ mix deps.update --all
Running dependency resolution

Failed to use "httpotion" (versions 3.0.0 to 3.0.2) because
  facebook_messenger (versions 0.2.0 and 0.3.0) requires ~> 2.2
  mix.exs specifies ~> 3.0.0

Failed to use "poison" (version 2.2.0) because
  phoenix (version 1.2.1) requires ~> 1.5 or ~> 2.0
  phoenix_facebook_messenger (versions 0.1.0 and 0.3.0) requires ~> 2.1.0

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

Please advise what shall I do to fix this "looping dependency error"?

**Comment by arjan** [comment]
If you use the github version of the package in your deps, it works:

```
      {:facebook_messenger, github: "nsomar/facebook_messenger"},
```
